demo

diff --git a/.github/workflows/update_csv.yml b/.github/workflows/update_csv.yml
--- a/.github/workflows/update_csv.yml
+++ b/.github/workflows/update_csv.yml
@@ -33,12 +33,14 @@ jobs:
                     # Get the custom filename associated with the URL
                     file_name="${csv_mapping[$url]}"
 
-                    # Download the CSV file
-                    if curl -o "new-csv-files/$file_name" "$url"; then
-                      echo "Downloaded $file_name successfully."
+                    curl -o "new-csv-files/$file_name" "$url" --progress
+
+                    # Check if the download was successful
+                    if [ $? -eq 0 ]; then
+                        echo "Downloaded $file_name successfully."
                     else
-                      echo "Download of $file_name failed."
-                      continue  # Skip to the next file on failure
+                        echo "Download of $file_name failed."
+                        continue  # Skip to the next file on failure
                     fi
 
                     # Compare the new CSV with the existing one
